FROM node:23-alpine3.19 AS builder
WORKDIR /app

#インストール
COPY  package.json  ./
RUN npm install

#ビルド
COPY . .
RUN npm run build


FROM node:23-alpine3.19 AS production
WORKDIR /app

# COPY .env ./
COPY package.json ./
RUN npm install --production

COPY --from=builder /app/next.config.* ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
ENV NODE_ENV=production

CMD [ "npm", "run", "start"]