FROM oven/bun:latest AS builder
WORKDIR /app

#インストール
COPY  package.json bun.lockb ./
RUN bun install

#ビルド
COPY . .
RUN bun run build


FROM oven/bun:latest AS production
WORKDIR /app
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"

CMD [ "bun", "server.js"]