FROM oven/bun:latest AS builder
WORKDIR /app

#インストール
COPY  package.json bun.lockb ./
RUN bun install

#ビルド
COPY . .
RUN bun run build


FROM oven/bun:latest AS production
WORKDIR /app

COPY .env ./
COPY package.json ./
RUN bun install --production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
ENV NODE_ENV=production

CMD [ "bun", "run", "start"]