name: ai-manga
on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "Dockerfile.prod"
      - "supabase"
      - "next.config.*"

env:
  PROJECT_NAME: ai-manga
  ORG_NAME: puragu
  REPO_NAME: ai-manga-infra
  DEPLOYMENT_FILE_NAME: 01-deployment.yaml

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "DATABASE_URL=${DATABASE_URL}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}" >> .env
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}" >> .env
          echo "AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}" >> .env
          echo "AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}" >> .env
          echo "AUTH_SECRET=${AUTH_SECRET}" >> .env
          echo "GEMINI_API_KEY=${GEMINI_API_KEY}" >> .env
          echo "AUTH_URL=https://4koma.agupiedpiper.com" >> .env
          echo "AUTH_REDIRECT_URL=https://4koma.agupiedpiper.com/api/auth" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.run_id }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest
          file: ./Dockerfile.prod
          context: .

  change-infrastructure-repo:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Commit and push changes to infrastructure repo
        run: |
          git config --global user.email "hrt_ioo1279@outlook.jp"
          git config --global user.name "potekichi"
          git clone https://potekichi:${{ secrets.INFRA_REPO_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git
          ls
          cd ${{ env.REPO_NAME}}/app
          sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:.*|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ github.run_id }}|' ${{ env.DEPLOYMENT_FILE_NAME }}
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push https://potekichi:${{ secrets.INFRA_REPO_PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.REPO_NAME }}.git